name_prefix   = "cmtr-ac643e5v-mod8"
location      = "East US"
student_email = "student@example.com"
git_repo_url  = "https://github.com/your-username/your-repo#main"
image_name    = "redis-flask-app"